on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run markdown linter
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'

      - name: Run spell checker
        uses: streetsidesoftware/cspell-action@v8
        with:
          files: '**/*.{md,yaml,yml}'
          incremental_files_only: false

      - name: Run YAML linter
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml

  build:
    name: Build ${{ matrix.os }}
    needs: quality_checks
    permissions:
      contents: read       # To read repository contents
      pull-requests: write # To write pull requests analysis results and artifacts

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            6.x
            10.x

      - name: Restore Tools
        run: >
          dotnet tool restore

      - name: Build Tests
        run: >
          dotnet build test/DemaConsulting.SpdxWorkflows.Tests

      - name: Run Windows Tests
        if: startsWith(matrix.os, 'windows')
        run: >
          dotnet test test/DemaConsulting.SpdxWorkflows.Tests
          --no-build
          --no-restore
          --verbosity normal
          --filter "TestCategory=AnyOS|TestCategory=Windows"

      - name: Run Linux Tests
        if: startsWith(matrix.os, 'ubuntu')
        run: >
          dotnet test test/DemaConsulting.SpdxWorkflows.Tests
          --no-build
          --no-restore
          --verbosity normal
          --filter "TestCategory=AnyOS|TestCategory=Linux"

      - name: Create Dotnet Tool
        run: |
          cd pack
          dotnet pack DemaConsulting.SpdxWorkflows.csproj -p:Version=${{ inputs.version }} -o .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            pack/*.nupkg
