name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x

    - name: Restore Tools
      run: >
        dotnet tool restore

    - name: Run Tests
      run: >
        dotnet test test/DemaConsulting.SpdxWorkflows.Tests
