name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x

    - name: Restore Tools
      run: >
        dotnet tool restore

    - name: Build Tests
      run: >
        dotnet build test/DemaConsulting.SpdxWorkflows.Tests

    - name: Run Windows Tests
      if: ${{ matrix.os =='windows-latest' }}
      run: >
        dotnet test test/DemaConsulting.SpdxWorkflows.Tests
        --no-build
        --no-restore
        --verbosity normal
        --filter "TestCategory=AnyOS|TestCategory=Windows"

    - name: Run Linux Tests
      if: ${{ matrix.os =='ubuntu-latest' }}
      run: >
        dotnet test test/DemaConsulting.SpdxWorkflows.Tests
        --no-build
        --no-restore
        --verbosity normal
        --filter "TestCategory=AnyOS|TestCategory=Linux"
